frontend/app/lib/session.ts
Fix #82
とりあえずエラー表示は1行で収まるようにした
=> [frontend] Print jose error message instead of stack trace (#82)

frontend/app/layout.tsx
ヘッダー（ナビゲーション）やフッター（チャット画面のテキスト入力）がボヨボヨ動かないようにするためにoverflow-hiddenをつけていたが、コンテンツがはみ出したときに表示できないのが不便だったので削除する。むしろチャット画面はカスタマイズしようかなと。
=> [frontend] Remove overflow-hidden from body（1行プルリク）

backend/src/user/user.controller.ts, frontend/app/lib/actions.ts, frontend/app/ui/user/avatar.tsx, frontend/app/ui/user/friends.tsx, frontend/app/user/[id]/page.tsx, frontend/components/ui/tooltip.tsx, frontend/package-lock.json, frontend/package.json
ユーザープロフィール画面にて友達を一覧表示するように実装しました。
Shadcnで追加したTooltipを利用してユーザ名をホバーした時に表示しています。
https://ui.shadcn.com/docs/components/tooltip
https://www.radix-ui.com/primitives/docs/components/tooltip
=> 友達一覧をユーザープロフィール画面に追加

frontend/app/layout.tsx, frontend/app/lib/actions.ts, frontend/app/lib/hooks/use-modal-store.ts, frontend/app/lib/modal-provider.tsx, frontend/app/room/[id]/page.tsx, frontend/app/room/[id]/sidebar-menu.tsx, frontend/app/room/[id]/sidebar.tsx, frontend/app/ui/room/ban-modal.tsx, frontend/components/ui/dialog.tsx, frontend/package-lock.json, frontend/package.json
roomにドロップダウンメニューを追加
BANの管理をするモーダルウィンドウを追加(BANが出来るだけでUNBANやBAN中かどうかの表示はまだ実装してません)
(Leave, setting, Add Userなどはハリボテ)
=> [frontend] Add modal window for ban management

backend/src/chat/chat.controller.spec.ts, backend/src/chat/chat.gateway.ts, backend/src/chat/chat.service.spec.ts, backend/src/chat/chat.service.ts, backend/src/common/events/block.event.ts, backend/src/common/events/unblock.event.ts, backend/src/room/room.controller.ts, backend/src/room/room.service.ts, backend/src/user/user.controller.spec.ts, backend/src/user/user.service.spec.ts, backend/src/user/user.service.ts, backend/test/chat-gateway.e2e-spec.ts
[backend]
- blockしているユーザーからのメッセージを受け取らないことを確認するテストを追加しました。
- unblockしたユーザーからのメッセージを受け取れることを確認するテストを追加しました。
- block・unblockのリアルタイム処理を追加しました。
- GET /room/:roomId/messagesでブロック中のユーザーからのメッセージを取得しないように変更しました。
block中にリロードするとblockしたユーザーのメッセージが全て見えなくなりunblockすると全て見える仕様です。
追加したテスト
|blocker|blocked|
|---|---|
|<img width="1440" alt="スクリーンショット 2024-01-11 19 19 22" src="https://github.com/usatie/pong/assets/90199432/c5de2348-0993-4091-ae67-6ee690135d8e">|<img width="1440" alt="スクリーンショット 2024-01-11 19 19 28" src="https://github.com/usatie/pong/assets/90199432/c62af4b2-1a38-4491-ae51-a861bc03cb73">
|block時リロード|unblock時リロード|
|---|---|
|<img width="1440" alt="スクリーンショット 2024-01-11 19 22 40" src="https://github.com/usatie/pong/assets/90199432/f156163c-1601-4851-8004-cab0210501d6">|<img width="1440" …
=> [backend] Processing blocks and unblocks in real-time

backend/src/chat/chat.service.ts, backend/test/chat-gateway.e2e-spec.ts
- kickしたユーザーがメッセージを送ったり、受け取ったり出来てしまっていたので修正しました。
- kickしたユーザーからのメッセージが届かないことを確認するテストを追加しました。
- kickしたユーザーが元いたroomのメッセージを受け取らないことを確認するテストを追加しました。
- kickのAPIが呼ばれて成功した時にsocketのroomからleaveするように修正しました。
- banも同様の現象が起きているので別PRで修正します。
追加したテスト
=> [backend] Fix kick user from room

backend/src/room/ban/ban.controller.spec.ts, backend/src/room/ban/ban.service.spec.ts, backend/src/room/ban/ban.service.ts, backend/test/chat-gateway.e2e-spec.ts
- banされたユーザーのメッセージが届かないことを確認するテストを追加しました。
- banされたユーザーが元いたルームからのメッセージを受け取らないことを確認するテストを追加しました。
- banのAPIが呼ばれた後にsocketのroomからleaveするように修正しました。
- frontend側でリロードせずに更新されるようにするためのbackend側の処理は別PRで追加します。
追加したテスト
=> [backend] Fix ban user from room

backend/src/room/room.controller.ts, backend/src/room/room.service.ts, backend/test/constants/user.ts, backend/test/room.e2e-spec.ts, backend/test/utils/app.ts
DMが既に作成済みかの情報と作成済みの場合はroomIdが必要だったため GET /room/direct/:userId APIを追加しました。
- GET /room/direct/:userIdのテストを追加しました。
- GET /room/direct/:userId APIを追加しました。
追加したテスト
=> [backend] Add API GET /room/direct/:userId

frontend/app/lib/actions.ts, frontend/app/lib/dtos.ts, frontend/app/room/[id]/dm-title.tsx, frontend/app/room/[id]/room-detail.tsx, frontend/app/room/[id]/sidebar-item.tsx, frontend/app/ui/room/setting-modal.tsx, frontend/app/ui/user/direct-message-button.tsx, frontend/app/user/[id]/page.tsx
- ユーザープロフィール画面にDMの作成orDM画面に飛ぶボタンを追加しました。
- DMに合わせて一部UIを修正しました。(DropDownMenuを無くしてban/leaveを出来ないように変更、room名になっていた箇所をDMの相手の名前に変更)
- DMのデフォルトのルーム名は仮置きでDMになっています。
- rooms-sidebar上で表示するDMの名前を相手のユーザー名にするよい方法が思いつかず、名前がDMのroomが複数表示されてクリックして中身を確認するまで区別がつかなくなっています。
=> [frontend] DM from user profile

backend/package.json, backend/src/auth/auth.controller.ts, backend/src/auth/auth.service.ts, backend/yarn.lock, compose.yml, frontend/app/(guest-only)/login/page.tsx, frontend/app/(guest-only)/signup/page.tsx
昨日の集まりの中で backend への リクエストだけでoauth 完結した方がシンプルなんじゃないかとアイデアを頂いた。
確かに! と思って、自分の中での front と back の理解を確認するためにも back だけで実装しました。
写真のpage の ... with 42 が、それぞれのbackend のリンクになっており、sign up と login ができるようになっています.
TODO
- "oauth は認証プロトコルではない" という言葉が理解できていない. 特にlogin 時のoauth の使い方に関わると思うが、安全なのかわからない
- profile の image を取得する
- [db] user の sign in 方法 ( 通常か 42oauth か) または複数許すのか
- [db] oauth のみでlogin するユーザもいるので、password を null 許容する
=> [backend] backend のendpoint を起点として oauth sign up and sign を行う

backend/prisma/migrations/20240118204714_add_mute_user_on_room_model/migration.sql, backend/prisma/schema.prisma, backend/src/app.module.ts, backend/src/chat/chat.gateway.ts, backend/src/chat/chat.module.ts, backend/src/room/mute/dto/create-mute.dto.ts, backend/src/room/mute/dto/update-mute.dto.ts, backend/src/room/mute/entities/mute.entity.ts, backend/src/room/mute/mute.controller.spec.ts, backend/src/room/mute/mute.controller.ts, backend/src/room/mute/mute.module.ts, backend/src/room/mute/mute.service.spec.ts, backend/src/room/mute/mute.service.ts, backend/test/chat-gateway.e2e-spec.ts, backend/test/room.e2e-spec.ts, backend/test/utils/app.ts
- PUT /room/:roomId/mutes/:userIdのテストを追加しました。
- GET /room/:roomId/mutesのテストを追加しました。
- DELETE /room/:roomId/mutes/:userIdのテストを追加しました。
- mute中のユーザーからmessageが届かないことを確認するテストを追加しました。
- mute期限後にmessageが届くことを確認するテストを追加しました。
- unmute後にmessageが届くことを確認するテストを追加しました。
- PUT /room/:roomId/mutes/:userIdを追加しました。
durationの指定がない場合は無期限のmuteになる仕様です。
- GET /room/:roomId/mutesを追加しました。
- DELETE /room/:roomId/mutes/:userIdを追加しました。
タイマー関数をmockに置き換えなどはまだ出来ていません。
テストの追加や修正により大きなPRになってしまっています🙏
追加したテスト
room.e2e-spec
chat-gateway.e2e-spec
修正したテスト
chat-gateway.e2e-specを少し修正
=> [WIP] mute user in room

frontend/app/lib/actions.ts, frontend/app/room/[id]/room-detail.tsx, frontend/app/room/[id]/sidebar-item.tsx
- muteに関するAPIを呼び出す関数をactionsに追加しました。
- Dropdown menuにmuteのボタンを追加しました。
- API呼び出しの結果が失敗していた時のユーザーへのフィードバックなどはまだ実装していません。
For 5minutes以外はDiscordに倣ったmute期間にしています。
=> [frontend] mute user in room

backend/prisma/migrations/20240121041719_add_oauth_enabled_culumn_with_user/migration.sql, backend/prisma/schema.prisma, backend/src/auth/auth.controller.ts, backend/src/auth/auth.service.ts, backend/src/user/entities/public-user.entity.ts, backend/src/user/entities/user.entity.ts, backend/test/user.e2e-spec.ts, compose.yml
- 環境変数が一つ設定し忘れていたので、redirect 先に飛べないようになってしまっていました。飛べるようにしました
- oauth signup したuser は適当なpassword が割り当てられていましたが、password 無しでsignup するようになりました
- user table の password が nonnull から null 許容になりました
- user table に oauthEnabled (Boolean) を追加しました.
- oauthEnabledが true な場合、sign in は oauth フローでのみ、false な場合 password フローでのみログインできます
TODO
- oauthEnabled が true なuser に、change password を成功させるのが不可能. ( 対応するか、あるいはコンポーネントを非表示にするか? )
=> [backend] oauth signup without password

frontend/app/ui/room/message-item.tsx
1 課題要件に、"with chat interface." と明示的に書いてあった
2 でも、chat room のところからは何をクリックしても user のprofile には飛べなかった
3 message に avatar をつけているところを、usertoolpic に差し替えることでprofile に飛ぶようにした。
(そもそも、profile 画像だけ見せたいところなんてない気がする ( avatar が表示されるところは全て profile に飛びたい ) ので
frontend の page.tsx では Avatar component の呼び出しをするところ全てusertoolpic　に差し替えてもいい気がする)
=> [frontend] user can go other user profile with chat interface.

backend/src/chat/chat.gateway.ts, backend/src/chat/chat.service.ts, backend/test/chat-gateway.e2e-spec.ts
- test を追加しました
- chat namespace にevent を追加しました
- invite-pong (誰かをinviteする)
- invite-cancel-pong (invite した人が invite をキャンセルする)
- approve-pong (invite を受理する) (invite してきていない相手のことは approve を送っても試合開始されない)
- match-pong (approve すると、両者に 当イベントでroomId が送られる) 
- block している されている user には invite 出来ない. ( server 側で制御 )
web socket を使うテストでは、綺麗に書けたんじゃないかなって思います!
- エラー時 (approve ) にクライアントにエラーメッセージを送信
TODO
- frontend側
- deny-pong
- message と name space は分けなくていいのか?
- 分けてない状態でエラーメッセージを送ろうとすると、'error' イベントが被る可能性がある。
=> [backend] invite to play

frontend/app/room/[id]/mute-menu.tsx, frontend/app/room/[id]/sidebar-item.tsx, frontend/app/ui/room/ban-item.tsx, frontend/app/ui/room/ban-modal.tsx, frontend/app/ui/room/invite-item.tsx, frontend/app/ui/room/invite-modal.tsx, frontend/app/ui/room/unban-item.tsx, frontend/components/ui/context-menu.tsx, frontend/components/ui/loader.tsx
- chat channelのcontext menu内のボタンを一度押したら処理が終了するまで再度押せないように修正しました。
- BAN、ADD USERも同様に修正し、処理中はpending状態の表示をするように変更しました。
- エラーが発生した際のユーザーへの通知や処理の修正、モーダルウィンドウ周りの修正(特にBAN)は別PRで行います。
=> [frontend] display pending status

backend/src/auth/auth.controller.ts, backend/src/auth/auth.service.ts, backend/test/chat-gateway.e2e-spec.ts, backend/test/online-status.e2e-spec.ts
[うさみさんのレビュー](https://github.com/usatie/pong/pull/230)
に対応しました
テストについて
- マジックナンバー
- 変数名をクリアに
- 関数名をクリアに
というところらへん
online status を API でとるかws でとるかは質問したいです
自分のメリデメの認識
API
- status の変化をリアルタイムに受け取れない ( reload しないと変更されない )
- 実装コストが低い
ws
- status の変化をリアルタイムに受け取れる
- 実装コストが少し高い? ( 複数の user の online status 部分を useStatus を使って管理する方法がパッと書けなかった)
=> Feat/backend/fix review/0131

backend/src/chat/chat.gateway.ts, backend/src/chat/chat.service.ts, backend/src/common/events/room-mute.event.ts, backend/src/common/events/room-unmute.event.ts, backend/src/common/events/room-update-role.event.ts, backend/src/room/mute/mute.controller.spec.ts, backend/src/room/mute/mute.service.spec.ts, backend/src/room/mute/mute.service.ts, backend/src/room/room.service.ts, backend/test/chat-gateway.e2e-spec.ts
- enter roomとupdate roomをした時にroom参加者がイベントを受け取れるか確認するテストを追加しました。
- enter roomとupdate roleした時にgatewayからclientにイベントを発行するように変更しました。
追加したテスト
=> [backend] Client notification on chat channel actions

frontend/app/lib/actions.ts, frontend/app/ui/auth/login-form.tsx
#237 
- signin時にServer Actionから`redirect`するとNavBarが更新されない
- （signout時にはNavBarも更新される）
- Server Actionからの返り値をもとに、Client Componentから`router.replace`することで対応した
=> [frontend] Fix redirect issue after signin by using router.replace from client component

frontend/app/lib/actions.ts, frontend/app/lib/client-socket-provider.tsx, frontend/app/ui/user/user-list.tsx
web socket で online status を管理する 変数を providerに用意しました。
以前使っていた、API で取得する群は一度消したので、online status の表示は静的になっています。
TODO:
- online status の情報を必要なページに共有する(use context?)
=> [frontend] manage users online status

backend/src/chat/chat.gateway.ts, backend/src/chat/chat.service.ts, backend/src/common/events/room-created.event.ts, backend/src/common/events/room-deleted.event.ts, backend/src/room/room.service.ts, backend/test/chat-gateway.e2e-spec.ts, backend/test/room.e2e-spec.ts
- roomを削除した時の通知とownerが退出した時の通知、roomの削除を確認するテストを追加しました。
- roomを削除した時に通知を出すように変更しました。
- ownerがroomを退出した時にroomを削除するように変更しました。
- create roomでuserIdsが存在した時にuserIdsのユーザー達をsocketのroomにjoinさせるように修正しました。
追加したテスト
=> [backend] handling owner leaves room and delete room notification

frontend/app/lib/client-socket-provider.tsx, frontend/app/lib/dtos.ts
- delete roomの通知のハンドリングを追加しました。
/room以下にいる時と/explore-roomsにいる時にリアルタイムに更新されます。
- messageの送信者が自分自身だった時にtoastを表示しないように修正しました。
- mute、unmute、updateRoleの通知時にtoastを表示しないように修正しました。
=> [frontend] Handling delete room notification

frontend/app/explore-rooms/explore-rooms.tsx, frontend/app/explore-rooms/page.tsx, frontend/app/lib/client-socket-provider.tsx, frontend/app/lib/hooks/useKick.ts, frontend/app/room/[id]/sidebar-item.tsx, frontend/app/room/rooms-sidebar.tsx
- roomのアクション(enter、leaveなど)関連のsocketイベントハンドリングをclient-socket-provider.tsxから削除し、実際にハンドリンが必要な場所に移動させました。
=> [frontend] Refactoring of socket event handling for room action

backend/src/auth/auth.controller.ts, backend/src/auth/auth.service.ts, backend/test/auth.e2e-spec.ts, backend/test/utils/app.ts
`DELETE /auth/2fa/disable`
とりあえずbackendで2faを非有効化するためのエンドポイントを作成しました。
=> :sparkles: Add 2FA disable endpoint

frontend/app/ui/auth/signup-form.tsx
callback のリンクがlogin になっていてsignup できていなかった。
訂正して、signup 用のエンドポイントをcallback に指定した
=> signup with 42 からサインアップできないバグ

frontend/app/pong/[id]/PongGame.ts
=> Fix an issue where the ball is not white in the dark mode

backend/src/chat/chat.gateway.ts, backend/test/chat-gateway.e2e-spec.ts, frontend/app/lib/client-socket-provider.tsx, frontend/app/lib/hooks/useKick.ts, frontend/app/lib/hooks/useRequestMatch.ts
- invite-pongをrequest-matchに変更しました。
- invite-cancel-pongをcancel-request-matchに変更しました。
- leaveをleave-roomに変更しました。
=> [Refactor] Rename socket event name

backend/src/chat/chat.gateway.ts, backend/test/chat-gateway.e2e-spec.ts, frontend/app/lib/client-socket-provider.tsx, frontend/app/lib/dtos.ts, frontend/app/lib/hooks/useRequestMatch.ts
- match request周りのsocketイベント名、関数名、変数名、型名などの名前を変更しました。
=> [Refactor] Rename socket events, functions, variables, etc. around match requests

backend/prisma/seed.ts
- seedのprotected roomにpasswordを追加して、後からexplore-roomsのjoinボタンを押して参加できるようにしました。
passwordは"password"です。
=> [backend] Add password to protected room in seed

backend/src/room/room.service.ts, backend/test/room.e2e-spec.ts, backend/test/utils/app.ts, frontend/app/lib/dtos.ts, frontend/app/room/rooms-sidebar.tsx
[backend]
- getRoomsのqueryがjoined=trueだった時のテストを追加しました。
- getRoomsのqueryがjoined=trueだった時にroomのメンバー情報も含めて返すように変更しました。
[frontend]
- RoomSidebarで表示していた参加済みroom一覧の表示room名をDMときはDM相手の名前を表示するように修正しました。
=> [frontend/backend] Fix dm room name

frontend/app/(guest-only)/login/error.tsx, frontend/app/lib/actions.ts, frontend/app/room/[id]/page.tsx, frontend/app/ui/user/accept-friend-request-button.tsx, frontend/app/ui/user/add-friend-button.tsx, frontend/app/ui/user/block-button.tsx, frontend/app/ui/user/cancel-friend-request-button.tsx, frontend/app/ui/user/direct-message-button.tsx, frontend/app/ui/user/reject-friend-request-button.tsx, frontend/app/ui/user/remove-friend-button.tsx, frontend/app/ui/user/unblock-button.tsx, frontend/app/user/[id]/not-found.tsx, frontend/app/user/[id]/page.tsx
- errorを投げたがuncaught errorになっていた箇所を修正しました。
- getUserでnullが返ってきた時にNotFoundページを表示するように修正しました。(404以外もnotFoundに行ってしまうので微妙)
- getRoomでerrorが投げられた時にerrorページが表示されていたのをNotFoundページを表示するように修正しました。(userと同じく404以外もnotFoundに行ってしまうので微妙かも)
- 各ユーザーページでユーザーがアクション(add frined、blockなど)を行った時のエラー通知をtoastでするように修正しました。
=> [frontend] Handle unhandled errors

backend/src/chat/chat.gateway.ts
- backend側で中身が空のメッセージを保存できるようになってしまっていたため、保存できないように修正しました。
=> [backend] Validated to prevent saving empty messages

backend/src/friend-request/friend-request.service.ts, backend/test/user.e2e-spec.ts
- フレンドリクエストのテストにブロック関連のテストを追加しました。
- 自分がblockしているユーザーにフレンドリクエストを送れない、受け取れないように修正しました。
- 自分をblockしているユーザーのフレンドリクエストを受け取れないように修正しました。
=> [backend] Prevent sending or receiving friend requests between users who have blocked each other

frontend/app/user/[id]/page.tsx
- 自分がblockしているユーザーのページでadd friendボタンとconfirmボタンをblock中は表示しないように変更しました。
=> [frontend] Change to not display the add friend button and confirm button while blocking

frontend/app/lib/client-socket-provider.tsx
-  client-socket-providerでuseAuthContextからcurrentUserを取得できる時だけsocket接続とイベント登録をするように修正しました。
=> [frontend] Fix to connect socket only when currentUser can be obtained

backend/src/auth/auth.module.ts
=> [backend] Extended expiration of access token
