- playground/02-gateways/.eslintrc.js
- playground/02-gateways/.gitignore
- playground/02-gateways/client/index.html
- playground/02-gateways/e2e/events-gateway/gateway.e2e-spec.ts
- playground/02-gateways/e2e/jest-e2e.json
- playground/02-gateways/jest.json
- playground/02-gateways/package-lock.json
- playground/02-gateways/package.json
- playground/02-gateways/peer.html
- playground/02-gateways/src/adapters/redis-io.adapter.ts
- playground/02-gateways/src/app.module.ts
- playground/02-gateways/src/events/events.gateway.spec.ts
- playground/02-gateways/src/events/events.gateway.ts
- playground/02-gateways/src/events/events.module.ts
- playground/02-gateways/src/main.ts
- playground/02-gateways/tsconfig.build.json
- playground/02-gateways/tsconfig.json
> :sparkles: Add WebSocket example

- Makefile
- docker-compose.yml
- test.sh
- web/Dockerfile
- web/html/index.html
- web/html/script.js
- web/nginx.conf
[compilerbookの最初のコミット](https://github.com/rui314/chibicc/commit/f722daaaae0606115df4ace5a852da23c1a5b0f3)を参考に、大体こんな感じで書いていくよーという最小限のスケルトンを作りました。
> :rocket: Initial commit for the skeleton project

- web/html/webrtc.html
すごく簡単な実装例ですが、p2pでチャットができます。
http://localhost:4242/webrtc.html
> :sparkles: Add WebRTC P2P chat example

- compose.yml
> Revert "Expose backend"

- backend/prisma/migrations/20231220141136_unique_username/migration.sql
- backend/prisma/schema.prisma
- backend/src/user/dto/create-user.dto.ts
- backend/src/user/entities/user.entity.ts
課題要件の`unique name`にするためにunique条件を追加
> [backend] Add unique constraint to User.name

- frontend/app/lib/actions.ts
- frontend/app/profile/change-password/page.tsx
- frontend/app/profile/layout.tsx
- frontend/app/ui/profile/avatar-form.tsx
- frontend/app/ui/profile/change-password-card.tsx
- frontend/app/ui/profile/change-password-form.tsx
- frontend/app/ui/profile/profile-form.tsx
- frontend/app/ui/profile/profile-item-form.tsx
- frontend/app/ui/profile/sidebar-nav.tsx
> パスワードの変更機能を実装

- backend/src/user/entities/public-user.entity.ts
- backend/src/user/user.controller.ts
- backend/test/user.e2e-spec.ts
- frontend/app/lib/actions.ts
- frontend/app/room/[id]/sidebar-item.tsx
- frontend/app/ui/user/add-friend-button.tsx
- frontend/app/ui/user/avatar.tsx
- frontend/app/ui/user/match-request-button.tsx
- frontend/app/user/[id]/page.tsx
激雑だけど、こんな感じで適当にとりあえず作っていく方がいいな多分
> 他人のプロフィール画面を見に行けるように

- backend/src/friend-request/dto/create-friend-request.dto.ts
- backend/src/friend-request/entities/friend-request.entity.ts
- backend/src/friend-request/entities/friend-requests.entity.ts
- backend/src/friend-request/friend-request.controller.ts
- backend/src/friend-request/friend-request.service.ts
- backend/test/user.e2e-spec.ts
- backend/test/utils/app.ts
- backend/test/utils/matcher.ts
- frontend/app/lib/actions.ts
- frontend/app/ui/sidebar-nav.tsx
- frontend/app/ui/user/accept-friend-request-button.tsx
- frontend/app/ui/user/cancel-friend-request-button.tsx
- frontend/app/ui/user/reject-friend-request-button.tsx
- frontend/app/ui/user/remove-friend-button.tsx
- frontend/app/user/[id]/page.tsx
> [frontend] 友達リクエスト、キャンセル、承諾、拒否、友達削除

- backend/prisma/seed.ts
- backend/src/history/history.controller.ts
- backend/src/history/history.service.ts
- frontend/app/lib/actions.ts
- frontend/app/ui/user/match-history.tsx
- frontend/app/user/[id]/page.tsx
> 対戦履歴の画面（プロフィール画面の中に）を実装

- frontend/app/ui/user/match-history.tsx
- frontend/app/ui/user/profile-item.tsx
- frontend/app/ui/user/stats.tsx
- frontend/app/user/[id]/page.tsx
統計情報といっても何を載せればいいかわからなかったので適当です。
あと、本当はこの計算はfrontendじゃなくてAPI（というかSQL）でやって返してあげるべき・・・！
（Stats用のAPIを作るのが面倒でサボっています）
> 対戦統計情報をユーザープロフィール画面に追加

- frontend/app/pong/MatchButton.tsx
- frontend/app/pong/[id]/PongBoard.tsx
detail: https://github.com/usatie/pong/issues/136
> Force new connections

- backend/src/adapters/authentication-io.adapter.ts
- backend/src/auth/auth.module.ts
- backend/src/auth/auth.service.ts
- backend/src/auth/jwt-auth.guard.ts
- backend/src/auth/jwt.strategy.ts
- backend/src/events/events.module.ts
- backend/src/events/pong-match.gateway.ts
- backend/src/user/user.guard-ws.ts
#92 
connectはできているが、requestはログインしていないと送れなくなっている
> Add authentication in webhook

- backend/src/events/events.gateway.ts
- backend/src/events/events.module.ts
- backend/src/history/history.module.ts
- backend/test/pong-gateway.e2e-spec.ts
- frontend/app/pong/[id]/PongBoard.tsx
> Create history when game ends

- backend/src/events/events.gateway.ts
- frontend/app/pong/[id]/PongBoard.tsx
- 観戦者に、”勝った”"負けた"みたいなログを送らないようにする
- 観戦者の startボタンをenableしないようにする
> Refactor viewer logging

- frontend/app/lib/actions.ts
- frontend/app/room/[id]/sidebar-menu.tsx
drop-down menuのLeaveボタンを押すとroomから退出するように変更しました。
> [frontend] Enable Leave in room drop-down menu

- backend/src/app.module.ts
- backend/src/room/ban/ban.controller.ts
- backend/src/room/ban/ban.service.ts
- backend/src/room/room.module.ts
- backend/test/room.e2e-spec.ts
- backend/test/utils/app.ts
[backend] GET /room/:id/bansのAPIとテストを追加しました。
> [backend] Add API GET /room/:id/bans

- frontend/app/lib/actions.ts
- frontend/app/lib/hooks/use-modal-store.ts
- frontend/app/room/[id]/sidebar-menu.tsx
- frontend/app/room/[id]/sidebar.tsx
- frontend/app/ui/room/ban-modal.tsx
[frontend]
- banの管理画面でbanのstatusの表示をし、unbanが出来るようにしました。
> Feat/frontend/display ban status and  can be unban

- frontend/app/lib/actions.ts
- frontend/app/lib/dtos.ts
- frontend/app/lib/hooks/use-modal-store.ts
- frontend/app/lib/modal-provider.tsx
- frontend/app/room/[id]/page.tsx
- frontend/app/room/[id]/sidebar-menu.tsx
- frontend/app/room/[id]/sidebar.tsx
- frontend/app/ui/room/setting-modal.tsx
- frontend/package-lock.json
- frontend/package.json
[frontend]
- ドロップダウンメニューから開けるroom設定のモーダルウィンドウの作成
- zodとuseFormを使った入力のバリデーション
参考サイト :
<https://github.com/react-hook-form/resolvers#zod>
<https://zod.dev/?id=discriminated-unions>
PUBLIC or PRIVATE
PROTECTED
> [frontend] Add modal window for room setting

- frontend/app/lib/actions.ts
- frontend/app/room/[id]/sidebar-item.tsx
backendのユーザーキックのAPI変更に合わせてfrontendのAPI呼び出し関数の修正をしました。
> [frontend] Fix API call function for kick user on room in frontend

- frontend/app/lib/actions.ts
- frontend/app/room/[id]/sidebar-item.tsx
- frontend/app/room/[id]/sidebar.tsx
ブロックの状態を反映させてリロードしてもキープするように修正しました。
> [frontend] keep block status

- frontend/app/lib/actions.ts
- frontend/app/lib/dtos.ts
- frontend/app/lib/hooks/use-modal-store.ts
- frontend/app/room/[id]/sidebar-item.tsx
- frontend/app/room/[id]/sidebar-menu.tsx
- frontend/app/room/[id]/sidebar.tsx
- frontend/app/ui/room/setting-modal.tsx
typoとaccessLevelの型をstringから
type AccessLevel = "PUBLIC" | "PRIVATE" | "PROTECTED"
に修正しました。
> [frontend] Fix typo and accessLevel types

- backend/src/room/dto/get-rooms-query.dto.ts
- backend/src/room/room.controller.ts
- backend/src/room/room.service.ts
- frontend/app/lib/actions.ts
- frontend/app/room/[id]/page.tsx
- frontend/app/room/[id]/rooms-sidebar.tsx
- frontend/app/room/[id]/users-sidebar.tsx
- frontend/app/room/layout.tsx
- frontend/app/room/page.tsx
- frontend/app/room/rooms-sidebar.tsx
- frontend/app/ui/room/ban-modal.tsx
- frontend/app/ui/room/setting-modal.tsx
> [WIP] ルーム一覧をチャット画面に追加中

- backend/src/chat/chat.gateway.ts
backendのchat.gatewayの不要なコードを削除しました。
> [backend] Remove unnecessary codes in chat.gateway

- frontend/app/ui/room/setting-modal.tsx
roomのコンテキストメニューのsettingからroomのaccess levelを変更できるように修正しました。
元々のaccess levelがPROTECTEDの時でもroomのnameだけでなく、
passwordも必ず入力しなければいけない仕様になってしまっているのが少し気になりますが良い方法が思いつかず、
passwordをそのままにする場合はユーザーに元のpasswordを入力してもらう形になっています。
|PROTECTED|PUBLIC or PRIVATE|
|---|---|
|<img width="1440" alt="スクリーンショット 2024-01-11 23 17 03" src="https://github.com/usatie/pong/assets/90199432/6efffabd-73cb-4cc6-aae8-cf82f533835c">|<img width="1440" alt="スクリーンショット 2024-01-11 23 16 28" src="https://github.com/usatie/pong/assets/90199432/083f6b88-ede0-48b6-8113-b8133cc9ab04">
無効な入力時のエラーメッセージ
|PROTECTED|PUBLIC or PRIVATE|
|---|---|
|<img width="1440" alt="スクリーンショット 2024-01-11 23 22 18" src="https://github.com/usatie/pong/assets/90199432/bb56596f-1d65-4c7d-a438-0c45027c3959">|<img width="1440" alt="スクリーンショット 2024-01-11 23 22 38" …
> [frontend] Enable room access level modification from the settings modal window

- frontend/app/lib/actions.ts
- frontend/app/lib/hooks/use-modal-store.ts
- frontend/app/lib/modal-provider.tsx
- frontend/app/room/[id]/sidebar-menu.tsx
- frontend/app/room/[id]/users-sidebar.tsx
- frontend/app/ui/room/invite-modal.tsx
コンテキストメニューのAdd userを押すと開けるユーザーをroomに招待(追加)するモーダルウィンドウを追加しました。
モーダルウィンドウ周りの細かい修正やエラー処理が微妙なところなどは別PRで修正します。
> [frontend] invite user to room

- frontend/app/lib/actions.ts
- frontend/app/ui/user/block-button.tsx
- frontend/app/ui/user/unblock-button.tsx
- frontend/app/user/[id]/page.tsx
ユーザープロフィールにブロック・アンブロックのボタンを追加しました。
> [frontend] Can be blocked from user profiles

- frontend/.eslintrc.json
- frontend/app/ui/room/setting-modal.tsx
- roomのsettingからアクセスレベルの変更が出来なくなっていたのを修正しました。
- 他のserver actionsを使っているコードとの一貫性を持たせるためにバリデーションをserver actions側でしたいですが、すぐに修正出来なさそうなので他の必須な機能の実装をした後に修正します。(zod, useFormを使用しているコードを使用せずに実装するなども同様)
> [frontend] Fix change access level in setting modal window

- backend/src/room/guards/enter-room.guard.ts
- backend/src/room/room.service.ts
room の password をハッシュ化して管理するようにしました
user のところでhash 化してるのを真似しただけなので大した変更はないです.
> [backend] room password save with hash

- backend/src/chat/chat.gateway.ts
- backend/test/chat-gateway.e2e-spec.ts
> Feat/backend/chat/invite pong/deny

- backend/src/chat/chat.controller.ts
- backend/src/chat/chat.service.ts
- backend/test/chat-gateway.e2e-spec.ts
- backend/test/utils/app.ts
- test 追加
- chat namespace に connect しているかどうかで online 判定
TODO
- login 直後に chat namespace  に登録されていると思い利用したがfrontend でそうなっているか確認する
> [backend] online status

- frontend/app/lib/client-socket-provider.tsx
- frontend/app/lib/dtos.ts
- frontend/app/lib/hooks/useBlock.ts
- frontend/app/lib/hooks/useInviteToGame.ts
- frontend/app/lib/hooks/useKick.ts
- frontend/app/lib/hooks/useMute.ts
- frontend/app/lib/hooks/useUpdateRole.ts
- frontend/app/room/[id]/mute-menu.tsx
- frontend/app/room/[id]/sidebar-item.tsx
- frontend/app/room/rooms-sidebar.tsx
- enter room、leave room、update role、 muteのイベント通知を受け取るように変更しました。
- sidebar-item内のロジックをカスタムフックに切り出して分離しました。
> [frontend] Handling notification

- frontend/app/lib/actions.ts
デプロイしてみないとわからないけど、これでうまくいってるといいな〜 #237
> :sparkles: Revalidate the layout after sign in and sign out

- frontend/app/ui/room/ban-item.tsx
- frontend/app/ui/room/unban-item.tsx
- ban modal周りの関数名の修正、不要な引数の削除をしました。
> [frontend] Refactor ban modal

- frontend/middleware.ts
- middlewareに/explore-roomsのpathを追加しました。
> [frontend] Add /explore-rooms path to middleware

- frontend/app/lib/actions.ts
- actions.ts内のredirectから不要なコードを削除しました。
> [frontend] Remove unnecessary code from redirect in server action

- backend/src/chat/chat.gateway.ts
- backend/src/chat/chat.module.ts
- backend/src/room/guards/enter-room.guard.ts
- backend/src/room/mute/mute.controller.ts
- backend/src/room/mute/mute.module.ts
- backend/src/room/mute/mute.service.ts
- backend/src/room/room.service.ts
- backend/test/chat-gateway.e2e-spec.ts
- backend/test/online-status.e2e-spec.ts
- frontend/app/explore-rooms/explore-rooms.tsx
- frontend/app/lib/client-socket-provider.tsx
- frontend/app/lib/hooks/useInviteToGame.ts
- frontend/app/lib/hooks/useKick.ts
- frontend/app/lib/hooks/useMute.ts
- frontend/app/lib/hooks/useOnlineStatus.ts
- frontend/app/lib/hooks/useUpdateRole.ts
- frontend/app/onlineProviders.tsx
- frontend/app/pong/JoinRoomForm.tsx
- frontend/app/room/[id]/mute-menu.tsx
- frontend/app/room/[id]/sidebar-item.tsx
- frontend/app/room/rooms-sidebar.tsx
- frontend/app/ui/auth/login-form.tsx
- frontend/app/ui/room/ban-item.tsx
- frontend/app/ui/room/invite-item.tsx
- frontend/app/ui/room/invite-modal.tsx
- frontend/app/ui/room/unban-item.tsx
- frontend/app/ui/user/user-list.tsx
`npx prettier@latest --write frontend backend --plugin=prettier-plugin-organize-imports`
> :recycle: Format code with prettier

- frontend/app/lib/actions.ts
- frontend/app/ui/settings/profile-form.tsx
- profileページでsaveボタンを押した時にupdateUser関数が呼ばれてnameとemailを更新できるように修正しました。
> [frontend] Update user from profile

- frontend/app/ui/settings/profile-form.tsx
- 前回PRをnpx prettier@latest --write frontend backend --plugin=prettier-plugin-organize-importsをかけ忘れてマージしてしまったためformatterをかけただけPRになっています🙏
> [frontend] Format code with prettier

- backend/src/chat/chat.service.ts
- backend/test/utils/matcher.ts
- frontend/app/lib/client-socket-provider.tsx
名前が目立たなくて、名前なのかただの出力のメッセージなのかわかりづらい（特にTest とか)
本当は名前の横にアイコンとか出て欲しい。
> [frontend] online status の出力に名前も出力する

- frontend/app/pong/JoinRoomForm.tsx
> Remove join room button

- backend/src/auth/auth.service.ts
- OAuthで401 Unauthorizedが返ってきた時に500 Internal server errorが表示されていたので401 Unauthorizedが表示されるように変更しました。
> [backend]  Modify to throw an UnauthorizedException when receiving a 401 Unauthorized response in OAuth

- frontend/app/ui/settings/change-password-form.tsx
- frontend/app/ui/settings/profile-form.tsx
- frontend/app/ui/user/accept-friend-request-button.tsx
- frontend/app/ui/user/add-friend-button.tsx
- frontend/app/ui/user/block-button.tsx
- frontend/app/ui/user/cancel-friend-request-button.tsx
- frontend/app/ui/user/reject-friend-request-button.tsx
- frontend/app/ui/user/remove-friend-button.tsx
- frontend/app/ui/user/unblock-button.tsx
- toast表示時にデベロッパーツールのconsoleにerrorを吐いていた箇所をuseEffectの中に入れて修正しました。
> [frontend] Fixed some toast to be placed inside useEffect

- frontend/app/settings/account/page.tsx
- frontend/app/settings/appearance/page.tsx
- frontend/app/settings/layout.tsx
- frontend/app/settings/notifications/page.tsx
> [frontend] delete page that is not used.
